eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka  客户端注册到多个eureka
spring:
  application:
    name: consumer